name: Deploy Terra Trial to PRO

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rsync and sshpass
        run: sudo apt-get install rsync sshpass -y

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Create robots.txt
        run: |
          echo "User-agent: *" > dist/robots.txt
          echo "Disallow: /" >> dist/robots.txt

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_PATH: ${{ secrets.VPS_PATH }}
        run: |
          sshpass -p "$SSH_PRIVATE_KEY" scp -o StrictHostKeyChecking=no -r dist/* head $VPS_USER@$VPS_HOST:$VPS_PATH

